name: release

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - v*

jobs:
  # Creates Release with just the changelog
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout bpfman
        uses: actions/checkout@v4
        
      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          if [[ ${GITHUB_REF#refs/*/} =~ "rc" ]]; then
            echo "PRE_RELEASE=true" >> $GITHUB_ENV
          else
            echo "PRE_RELEASE=false" >> $GITHUB_ENV
          fi
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ./changelogs/CHANGELOG-${{ env.RELEASE_VERSION }}.md
          prerelease: ${{ env.PRE_RELEASE }}
